# Generated by Django 3.1.7 on 2021-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('g', 'group'), ('i', 'individual')], max_length=1, verbose_name='Тип уроков')),
            ],
        ),
    ]
