# Generated by Django 3.1.7 on 2021-05-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
