# Generated by Django 3.1.7 on 2021-05-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20210506_0734'),
        ('classes', '0002_auto_20210517_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.languages', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=3, null=True, verbose_name='Номер группы'),
        ),
    ]
