# Generated by Django 3.1.7 on 2021-05-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20210515_1429'),
        ('students', '0004_auto_20210518_0931'),
        ('classes', '0003_auto_20210518_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='instructors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructors', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(to='students.Students', verbose_name='Студенты'),
        ),
    ]
