# Generated by Django 3.1.7 on 2021-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210518_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Номер группы'),
        ),
    ]
