# Generated by Django 3.1.7 on 2021-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210519_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(default='Частный урок', max_length=20, null=True, verbose_name='Номер группы'),
        ),
    ]
